# Task 3 - Data Cleaning

## Objective
To clean a delibarately messy dataset and transform it into a clean, analysis-ready dataset using Python, Pandas and NumPy.

## Tools Used
- Python
- Pandas
- NumPy
- Jupyter Notebook

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv(r"C:\Users\hemas\OneDrive\Desktop\Python\Titanic-Dataset.csv")

In [16]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df.shape

(891, 12)

In [18]:
print("Rows : ",df.shape[0])
print("Columns : ",df.shape[1])

Rows :  891
Columns :  12

## 1.Initial Data Inspection
First, the dataset is inspected to understand its structure, dimesions, column names, data types and missing values.

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [20]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [21]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [22]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 2.Data Quality Report
A data quality assessments is performed before cleaning the dataset to identify potential issues that may affect the accuracy and reliability of further analysis.
It mainly focuses on :
- Missing values
- Duplicate records
- Data type issues
- Value range anamolies

### Null count per column and Data types

In [23]:
quality_report = pd.DataFrame({
    "Column":df.columns,
    "Null_Count":df.isnull().sum().values,
    
    "Data_Type":df.dtypes.astype(str).values
})
quality_report

         Column  Null_Count Data_Type
0   PassengerId           0     int64
1      Survived           0     int64
2        Pclass           0     int64
3          Name           0       str
4           Sex           0       str
5           Age         177   float64
6         SibSp           0     int64
7         Parch           0     int64
8        Ticket           0       str
9          Fare           0   float64
10        Cabin         687       str
11     Embarked           2       str

### Duplicate analysis

In [24]:
df[df.duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [25]:
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:",duplicate_count)
if duplicate_count > 0:
    print("Duplicate rows found.")
else:
   print("No Duplicate rows found.")

Number of duplicate rows: 0
No Duplicate rows found.

### Value range anamolies

In [26]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [27]:
numeric_columns = df.select_dtypes(include=np.number).columns
for column in numeric_columns:
    print(f"\n{column}")
    print("Minimum:",df[column].min())
    print("Maximum:",df[column].max())
print("\n")
print("Negative ages:",(df["Age"]<0).sum())
print("Negative fares:",(df["Fare"]<0).sum())
print("Invalid Survival values:",
      (~df["Survived"].isin([0,1])).sum())
print("Invalid Pclass values:",
      (~df["Pclass"].isin([1,2,3])).sum())

PassengerId
Minimum: 1
Maximum: 891

Survived
Minimum: 0
Maximum: 1

Pclass
Minimum: 1
Maximum: 3

Age
Minimum: 0.42
Maximum: 80.0

SibSp
Minimum: 0
Maximum: 8

Parch
Minimum: 0
Maximum: 6

Fare
Minimum: 0.0
Maximum: 512.3292


Negative ages: 0
Negative fares: 0
Invalid Survival values: 0
Invalid Pclass values: 0

## 3.Data Handling
Missing values can affect statistical analysis and machine learning models. Therefore, the missing values identified during the data quality assessment are handled using appropriate techniques based on the data type and the proportion of missing values.

### Missing Value Analysis
The number and percentage of missing values are calculated for each column to determine the extent of missing data before appplying any cleaning technique.

In [28]:
missing_report = pd.DataFrame({
    "Missing_Count":df.isnull().sum(),
    "Missing_Percentage":(df.isnull().mean()*100).round(2)
})
missing_report

             Missing_Count  Missing_Percentage
PassengerId              0                0.00
Survived                 0                0.00
Pclass                   0                0.00
Name                     0                0.00
Sex                      0                0.00
Age                    177               19.87
SibSp                    0                0.00
Parch                    0                0.00
Ticket                   0                0.00
Fare                     0                0.00
Cabin                  687               77.10
Embarked                 2                0.22

#### Missing value treatment decisions
The missing values are handled according to the data type and the proportion of missing values in each column.
- Age: Missing numerical values are replaced with the median because the median is less affected by extreme values.
- Embarked: Missing categorical values are replaced with the mode, which represents the most frequently occuring category.
- Cabin: The column contains a large proportion of missing values.
  
Since reliable imputation is difficult, the column is removed.

In [29]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [30]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [31]:
df = df.drop(columns=["Cabin"])

#### Verification after missing value treatment
After applying the selected treatment methods, the dataset is checked again to confirm that the missing values have been handled successfully.

In [32]:
missing_after = pd.DataFrame({
    "Missing_Count":df.isnull().sum(),
    "Missing_percentage":(df.isnull().mean()*100).round(2)
})
missing_after

             Missing_Count  Missing_percentage
PassengerId              0                 0.0
Survived                 0                 0.0
Pclass                   0                 0.0
Name                     0                 0.0
Sex                      0                 0.0
Age                      0                 0.0
SibSp                    0                 0.0
Parch                    0                 0.0
Ticket                   0                 0.0
Fare                     0                 0.0
Embarked                 0                 0.0

In [33]:
print("Total missing values after treatment:",df.isnull().sum().sum())

Total missing values after treatment: 0

## 4.Duplicate Removal
Duplicate rows can cause records to be counted more than once and may lead to inaccurate analysis.
Therefore, duplicate records are identified and removed from the dataset.

### Duplicate Row Analysis
The dataset is checked for exact duplicate rows before removing them.
The number of duplicate records is recorded for comparisions with the final cleaned dataset.

In [34]:
duplicate_count = df.duplicated().sum()
print("Duplicate rows before removed:",duplicate_count)

Duplicate rows before removed: 0

### Remove duplicates
Exact duplicate rows, if present, are removed using the Pandas drop_duplicates() method. This ensures that each identical record is represented only once in the cleaned dataset.

In [35]:
df = df.drop_duplicates()

### Verification after duplicate removal
The dataset is checked again to confirm that no exact duplicated rows remain after the cleaning process.

In [36]:
duplicate_after = df.duplicated().sum()
print("Duplicate rows after removal:",duplicate_after)

Duplicate rows after removal: 0

In [37]:
print("Duplicate rows removed:",duplicate_count-duplicate_after)

Duplicate rows removed: 0

## 5.Standardisation
Text and Categorical columns are checked for inconsistent formatting, such as leading or trailing spaces and differences in capitalization.

Standardising these values ensures that the same categroy is represented consistently throughout the dataset.

### Inspect Categorical values
The unique values in categorical columns are examined before standardisation to identify inconsistent representations.

In [38]:
categorical_columns = df.select_dtypes(include=["object","string"]).columns
for column in categorical_columns:
    print(f"\n{column}:")
    print(df[column].unique())

Name:
<StringArray>
[                            'Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
                              'Heikkinen, Miss. Laina',
        'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
                            'Allen, Mr. William Henry',
                                    'Moran, Mr. James',
                             'McCarthy, Mr. Timothy J',
                      'Palsson, Master. Gosta Leonard',
   'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
                 'Nasser, Mrs. Nicholas (Adele Achem)',
 ...
                                  'Markun, Mr. Johann',
                        'Dahlberg, Miss. Gerda Ulrika',
                       'Banfield, Mr. Frederick James',
                              'Sutehall, Mr. Henry Jr',
                'Rice, Mrs. William (Margaret Norton)',
                               'Montvila, Rev. Juozas',
                        'Graham, Miss. Margaret Edith',
            'Johnston, Miss. Catherine Helen "Carrie"',
                               'Behr, Mr. Karl Howell',
                                 'Dooley, Mr. Patrick']
Length: 891, dtype: str

Sex:
<StringArray>
['male', 'female']
Length: 2, dtype: str

Ticket:
<StringArray>
[       'A/5 21171',         'PC 17599', 'STON/O2. 3101282',
           '113803',           '373450',           '330877',
            '17463',           '349909',           '347742',
           '237736',
 ...
           '349212',           '349217',           '349257',
             '7552', 'C.A./SOTON 34068',  'SOTON/OQ 392076',
           '211536',           '112053',           '111369',
           '370376']
Length: 681, dtype: str

Embarked:
<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

### Apply Standardisation
Leading and trailing whitespace is removed from text values, and categorical values are converted to a consistent case where appropriate.

In [39]:
for column in categorical_columns:
    df[column] = df[column].astype(str).str.strip()

In [40]:
df["Sex"] = df["Sex"].str.lower()
df["Embarked"] = df["Embarked"].str.upper()

### Verification after Standardisation
The categorical columns are checked again to confirm that text formatting is cosistent after standardisation.

In [41]:
print("Sex values:")
print(df["Sex"].unique())

print("\nEmbarked values:")
print(df["Embarked"].unique())

Sex values:
<StringArray>
['male', 'female']
Length: 2, dtype: str

Embarked values:
<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

## 6.Outlier Detection
Outliers are observations that differ substantially from the majority of values in a numerical column. The Interquartile Range (IQR) method is used to identify potential outliers.

IQR = Q3-Q1

Lower Bound = Q1-1.5*IQR

Upper Bound = Q3+1.5*IQR

Values below the lower bound or above the upper bound are considered potential outliers.

### Identifying Potential Outliers
The IQR  method is applied to the numerical columns in the dataset.
The number of potential outliers is calculated for each numerical column.

In [42]:
numeric_columns = df.select_dtypes(include=np.number).columns
outlier_report = []
for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3-Q1
    lower_bound = Q1-1.5*IQR
    upper_bound = Q3+1.5*IQR
    outliers = df[
    (df[column]<lower_bound)|(df[column]>upper_bound)
    ]
    outlier_report.append({
    "Column":column,
    "Q1":Q1,
    "Q3":Q3,
    "IQR":IQR,
    "Lower_Bound":lower_bound,
    "Upper_Bound":upper_bound,
    "Outlier_Count":len(outliers)
    })
outlier_report = pd.DataFrame(outlier_report)
outlier_report

,Column,Q1,Q3,IQR,Lower_Bound,Upper_Bound,Outlier_Count
0,PassengerId,223.5000,668.5,445.0000,-444.000,1336.0000,0
1,Survived,0.0000,1.0,1.0000,-1.500,2.5000,0
2,Pclass,2.0000,3.0,1.0000,0.500,4.5000,0
3,Age,22.0000,35.0,13.0000,2.500,54.5000,66
4,SibSp,0.0000,1.0,1.0000,-1.500,2.5000,46
5,Parch,0.0000,0.0,0.0000,0.000,0.0000,213
6,Fare,7.9104,31.0,23.0896,-26.724,65.6344,116

### Outlier Treatment Decision

The IQR method identified potential outliers in Age, SibSp, Parch and
Fare. However, statistical outliers are not automatically considered
data errors.

The identified observations were reviewed based on the meaning of each
variable. The extreme values can represent genuine passenger
characteristics, such as older passengers, larger family groups, or
higher ticket fares.

Therefore, the identified outliers are retained rather than removed or
capped. This prevents the loss of valid information from the dataset.

### Outlier Summary

No observations are removed solely because they were identified as
statistical outliers using the IQR method. The outlier detection results
are documented for transparency, while valid extreme observations are
retained for further analysis.

## 7.Data Type Correction

The data types of all columns are reviewed to ensure that they are
appropriate for their intended use.

Identifier columns are treated as strings, numerical measurements are
stored using appropriate numeric types, and categorical columns are
stored as text values.

### Current Data Types

The current data types are reviewed before applying any necessary
corrections.

In [43]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

### PassengerId Data Type

PassengerId is an identifier and does not represent a numerical
quantity. Therefore, it is converted from an integer to a string so
that it is not accidentally treated as a numerical measure during
analysis.

In [44]:
df["PassengerId"] = df["PassengerId"].astype(str)

### Numerical Column Correction

The numerical columns are explicitly converted to appropriate numeric
data types to ensure that mathematical and statistical operations can
be performed correctly.

In [45]:
numeric_columns = ["Survived","Pclass","Age","SibSp","Parch","Fare"]
for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

### Categorical Column Correction

Categorical columns are stored as text values so that categories such
as gender and embarkation port are handled consistently.

In [46]:
categorical_columns = ["Name", "Sex", "Ticket", "Embarked"]
for column in categorical_columns:
    df[column] = df[column].astype(str)

### Verification of Data Types

The data types are checked again after correction to confirm that the
columns have appropriate data types.

In [47]:
df.dtypes

PassengerId        str
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

## 8.Before vs After Cleaning Summary

In [48]:
print("Current number of rows:",len(df))

Current number of rows: 891

### Cleaning Summary Table

In [53]:
expected_types = {
    "PassengerId": "string",
    "Survived": "numeric",
    "Pclass": "numeric",
    "Name": "string",
    "Sex": "string",
    "Age": "numeric",
    "SibSp": "numeric",
    "Parch": "numeric",
    "Ticket": "string",
    "Fare": "numeric",
    "Embarked": "string"
}
correct_types = 0
for column, expected in expected_types.items():
    actual = str(df[column].dtype)
    if expected == "string" and actual in ["object","string","str"]:
        correct_types += 1
    elif expected == "numeric" and pd.api.types.is_numeric_dtype(df[column]):
        correct_types += 1
total_columns = len(expected_types)
summary_table = pd.DataFrame({
    "Metric": [
        "Total Null Values",
        "Duplicate Rows",
        "Number of Rows",
        "Number of Columns",
        "Correct Data Types"
    ],
    "After Cleaning": [
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df.shape[0],
        df.shape[1],
        f"{correct_types}/{total_columns}"
    ]
})
summary_table

               Metric After Cleaning
0   Total Null Values              0
1      Duplicate Rows              0
2      Number of Rows            891
3   Number of Columns             11
4  Correct Data Types          11/11

## 9..Export Cleaned Dataset

The cleaned dataset is exported to a new CSV file. The original dataset
is preserved separately to maintain the raw data and ensure
reproducibility.

In [54]:
df.to_csv("titanic-cleaned.csv", index = "False")
print("Cleaned dataset saved successfully as 'titanic-cleaned.csv'")

Cleaned dataset saved successfully as 'titanic-cleaned.csv'

In [56]:
import os
print("File exists:", os.path.exists("titanic-cleaned.csv"))

File exists: True

## 10.Conclusion

The Titanic dataset was successfully cleaned and transformed into an
analysis-ready dataset.

The cleaning process included:

- Data quality assessment
- Missing value analysis and treatment
- Duplicate detection and removal
- Text and categorical value standardisation
- IQR-based outlier detection
- Outlier treatment decision
- Data type correction
- Before-and-after data quality comparison
- Exporting the cleaned dataset

Missing values were handled using appropriate techniques based on the
type and extent of missing data. Potential statistical outliers were
reviewed and retained when they represented plausible observations
rather than confirmed data errors.

The final cleaned dataset was saved as a new CSV file without modifying
the original dataset.